### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by preguntator** [Zeex/pawn#109]
Good evening, 

First of all, I apologize because it is not really an issue, but just questions. First of all, In the presentation, you are saying 

> main goal of the project is to re-create changes that were previously made by the devs

Is this goal reached ? Are you now fixing only bugs ? When I ask this, it is for know if this compiler is enough stable ?

With this computer, is the performance better than the other compiler ?

And I download an issue: I see two folders (bin and libs) where does I have to put them ? to use this compiler

Thanks

**Comment by Y-Less** [comment]
This compiler has gone way beyond the minor changes made to the old compiler, with new features and bug fixes.  If you have a choice, use this one without question!

**Comment by preguntator** [comment]
Thanks for your answer! I will as a consequence use it. However can you explain me what i have to do with  files : pawndisasm, pawndisasm.pdb, I never saw them in the old compiler. same for pawncc.pdb and also pawnc.lib

**Comment by Y-Less** [comment]
pawndisasm is a disassembler (not quite the same as a decompiler - it just dumps assembly). .pdb and .lib files can be ignored, they are for compiler development and debugging.

**Comment by preguntator** [comment]
Thanks
