### ISSUE TITLE
Accessing array elements whose base address and index is already known [Optimization]

### ISSUE THREAD

**Issue by YashasSamaga** [Zeex/pawn#112]
```
new arr[123];
strcat(arr[4], ...);
```

The compiler generates the following assembly for the above code

```
const.pri 2ec
add.c 10
push.pri
```

which is equivalent to
`push.c 2fc`

Since the address and the index is already known, the compiler should push the address of the element directly instead of doing the calculations which would've been done in the case of a variable index.

The optimization should be done whenever the index and the base address are already known.

---

`funcname[5] = cmdtext[4];`

The compiler gives the following assembly output

```
addr.pri fffff9b4
add.c 14
push.pri
const.pri 2ec
add.c 10
load.i
pop.alt
stor.i
```

Firstly, what is the need for pushing the address and later poping? Why not reverse the process, i.e: do the right hand side first then do the left. I guess there is a reason why it isn't done directly (why would someone simply push and pop? there must've been a reason for it to be done that way). Not sure what the reason could be.

Combined with the earlier optimization suggestion, the above code would be equivalent to the following,

```
load.pri 2fc    
addr.altfffff9c8
stor.i
```

**Comment by oscar-broman** [comment]
I'm very glad these optimizations do not happen, otherwise a lot of code scanning includes (such as samp-observer) would not be possible.

**Comment by YashasSamaga** [comment]
The optimizations could be made toggle-able so that someone who wants to debug will ask the compiler not to do the optimizations whereas someone who wants to build release version could do all the optimizations just like it is done in IRL software development.

**Comment by oscar-broman** [comment]
When I say code scanning I mean reading the AMX at runtime.

If this were to be added, it must be opt-in rather than opt-out, because it would break things.
