### ISSUE TITLE
Using an array (enumerator and specifically a string) in a ternary operator causes the compiler to crash

### ISSUE THREAD

**Issue by AndySedeyn** [Zeex/pawn#113]
I failed at finding any reference to this issue when it comes to known bugs or fixes for it. After reporting it on the SA-MP forum (http://forum.sa-mp.com/showthread.php?p=3757995) and it being confirmed to be a compiler bug (only by one person at the point of posting this issue), I decided to report it here too. Perhaps just so you've heard about it.

The following code crashes the compiler:
```PAWN
SendTaggedMessageToPlayer(playerid, TYPE_ADMIN, "%p has been kicked by the server by %s, reason: %s", playerid, ((kickerid == INVALID_PLAYER_ID) ? ("The Server") : (Player[kickerid][epd_Username])), reason);
```
It is specifically traceable to ```Player[playerid][epd_Username]``` as replacing it with a literal string seems to fix it.

**Comment by Y-Less** [comment]
Is this in the updated compiler or default?  I thought that issue had been addressed already, but Zeex will know more.  I did a quick test and it works fine for me with his compiler.

**Comment by Y-Less** [comment]
My test code, in case you have some different circumstances (a fully compilable test-case is always more helpful than a single line of code, for future reference):

```pawn
#include <a_samp>

new arr[10][32];

main()
{
	new a = 1, b = 4;
	printf("%s", a ? ("hello") : (arr[b]));
	printf("%s", a ? ("hello") : (arr[b][3]));
}
```

**Comment by AndySedeyn** [comment]
Yeah, it seems to work. Thank you!

**Comment by AndySedeyn** [comment]
It is still prompting a strange error with both my code and yours:
```
error 033: array must be indexed (variable "-unknown-")
```
It's on line 9 of your code:
```PAWN
printf("%s", a ? ("hello") : (arr[b][3]));
```

**Comment by Y-Less** [comment]
Errors aren't crashes.  That is the compiler working correctly.
