### ISSUE TITLE
Pawn compiler 3.10.20160702 segfault on linux x64

### ISSUE THREAD

**Issue by xxmitsu** [Zeex/pawn#114]
Hello,
I'm using 
`Pawn compiler 3.10.20160702                     Copyright (c) 1997-2006, ITB CompuPhase`
version of your compiler, downloaded from the releases section.

with the following versions of glibc packages:

glibc-devel-2.17-106.el7_2.8.x86_64
glibc-devel-2.17-106.el7_2.8.i686
glib2-2.42.2-5.el7.x86_64
glibc-2.17-106.el7_2.8.x86_64
glib2-2.42.2-5.el7.i686
dbus-glib-0.100-7.el7.x86_64
glibc-headers-2.17-106.el7_2.8.x86_64
glibc-2.17-106.el7_2.8.i686
glibc-common-2.17-106.el7_2.8.x86_64

 however suddenly it started to segfault.

Full backtrace can be found here: http://pastebin.com/svN3Eznn

Thank you in advance for the help!

**Comment by ziggi** [comment]
Linux version has more segfaults. I use little bit modified version without two lines (see pr #64). Without these lines compiler works pretty good (not perfect). You can download binary: [libpawnc.so](https://github.com/Open-GTO/Open-GTO/blob/master/compiler/libpawnc.so), [pawncc](https://github.com/Open-GTO/Open-GTO/blob/master/compiler/pawncc).

**Comment by xxmitsu** [comment]
Thank you, it seems that is compiling fine with your modified version.
Do you happen to know what is the reason behind this ?

**Comment by ziggi** [comment]
> Do you happen to know what is the reason behind this ?

See pr #115

**Comment by xxmitsu** [comment]
Hello,

This issue can be closed when the specified fix will reach upstream.
Thanks again for investigating and finding a proper solution!

**Comment by Zeex** [comment]
This was fixed by #115.
