### ISSUE TITLE
unused public stock variables end up in the p-code

### ISSUE THREAD

**Issue by YashasSamaga** [Zeex/pawn#119]
> Stock variables are useful in combination with stock functions. A public variable may be declared as “stock” as well —declaring public variables as “public stock” enables you to declare al public variables that a host application provides in an include ﬁle, with only those variables that the script actually uses winding up in the P-code ﬁle.

public stock variables are ending up in the P-Code when it shouldn't.

**Comment by Y-Less** [comment]
https://github.com/Zeex/pawn/issues/71

**Comment by Y-Less** [comment]
Looking back, I think the original issue was that unused public variables issued warnings, while unused public functions didn't.  However, they could be used, but just not obviously so (a few libraries use and access them exclusively by name).  The solution at the time was to make `public stock` suppress the warning but always keep them; but I think the better solution is to never have the warning in the first place, as with the functions, and use `stock` to remove them when they aren't explicitly used.

**Comment by YashasSamaga** [comment]
I have another issue with the scope of public variables. Public functions are accessible throughout the script irrespective of the location where it is declared. But in case of public variables, it is required that they are declared before use.

The PAWN Language Guide says the following,
> Public variables behave like global variables, 

So I really wonder if it should be labeled as a bug.

**Comment by Y-Less** [comment]
Global variables behave like that too, so it is accurate.

**Comment by YashasSamaga** [comment]
https://github.com/Zeex/pawn/pull/128
