### ISSUE TITLE
Float operator-- gets replaced with float operator++

### ISSUE THREAD

**Issue by spmn** [Zeex/pawn#126]
```sourcepawn
#include <a_samp>

main()
{
	new Float:f = 1.0;
	f--;
	printf("%f", f);
}
```
Expected output: 0.000000
Real output: 2.000000

**Comment by YashasSamaga** [comment]
-- calls the wrong function (tested with prints).
-- calls the ++ function. 
++ calls the ++ function.

Interestingly, the -- operator code does not appear in the assembly output even if -- is used. But operator++ appears if -- is used and ++ is not used.

**Comment by spmn** [comment]
Oops, my bad. My compiler batch file invoked original pawncc instead of Zeex's one, so I thought I was using the latest version.
I guess there's no point in keeping this issue opened.
