### ISSUE TITLE
Minor revision constant.

### ISSUE THREAD

**Issue by Y-Less** [Zeex/pawn#132]
#5 added a new version of `__Pawn`, which has been useful, but since then this compiler has moved to using `3.10.date` for its versions and doesn't bump the minor version at all it seems (which again is fine).  However, if there's a fix in one version but not other it would be useful to know (as just discussed in #131).  Maybe a BCD `__Revision` constant such as `0x20170120` (which would be directly comparable for ordering for at least the next 6000 years).

**Comment by Zeex** [comment]
Good idea. I went with a plain number instead of a date for simplicity, it will be incremented on each release. The new constant is called `__PawnBuild`.

**Comment by Y-Less** [comment]
Fair enough, I just suggested the date because that was the scheme you already seemed to be using, but as long as it increases the absolute values don't matter.  Thanks.

**Comment by Zeex** [comment]
Yeah... I know :smiley: This would probably be a patch version if we were following SemVer or could also increment the minor version like you said.

Perhaps something like `__PawnVersion` which included all 3 fields would be a better solution now that I think about it again, hmm...
