### ISSUE TITLE
Proposal: enum limited to single file scope

### ISSUE THREAD

**Issue by Yiin-** [Zeex/pawn#134]
So it could be possible to do

a.pwn
```
static enum Foo {
  E_FOO,
  E_BAR
}
```

b.pwn
```
static enum Foo {
  E_FOO = 2,
  E_BAR
}
```

main.pwn
```
#include "a.pwn"
#include "b.pwn"

enum Foo {
  E_FOO,
  E_BAR
}
```

**Comment by Zeex** [comment]
This will be available in the next release. It's mostly done but needs some polish.

You can try now: https://ci.appveyor.com/project/Zeex/pawn/build/149/artifacts
