### ISSUE TITLE
define patterns - (), <>, ::, etc. are considered to be the same

### ISSUE THREAD

**Issue by YashasSamaga** [Zeex/pawn#142]
Most of us are already aware of it but I am surprised that an issue hasn't been raised. Maybe PAWN was designed to be that way? I wasn't able to find a statement in the guide which supported the idea. So it is a bug?

`#define abc<%0>`
`#define abc(%0)`

` warning 201: redefinition of constant/macro (symbol "abc(%0)")`

**Comment by VVWVV** [comment]
The compiler [compares](https://github.com/Zeex/pawn/blob/master/source/compiler/sc2.c#L1451) only the name of the macro, i.e. not the whole macro.

**Comment by Y-Less** [comment]
There are three parts to a macro - the name, the search pattern, and the replacement.  The name is everything at the start of a macro that is a valid symbol character: `0-9`, `a-z`, A-Z`, `_`, and `@`.  The first non-symbol character marks the end of the name, the first whitespace marks the end of the search pattern, and those two things might be the same.  So doing:

```pawn
#define abc<%0>
#define abc(%0)
```

Is saying create a macro called 'abc' that searches for the text 'abc' followed by anything in angle brackets, then create another macro ALSO called 'abc' that searches for the text 'abc' followed by anything in brackets.  You can't have two symbols with the same name anywhere in PAWN, and macros are no exception.  This is also why to remove the macro you just type `#undef abc'.

**Comment by Y-Less** [comment]
An analogy to what you're thinking would be function overloading.  This is invalid C, but valid C++:

```c
int Function(bool x)
{
    return 0;
}

int Function(long x, int y)
{
    return 0;
}
```

**Comment by Y-Less** [comment]
And of course PAWN doesn't support function overloading at all (except operator overloading, but that's a special case).

**Comment by Y-Less** [comment]
If you want vastly more information than probably anyone needs on this, and you can find a copy, check my pre-processor topic.  pawn-lang.pdf has a little bit, but I don't think the macros were ever envisioned to go beyond `#define CONSTANT 5` and `#define FUNCTION(%0,%1) ((%0) + (%1))`.  It is honestly amazing that it can handle what we put it through!

**Comment by YashasSamaga** [comment]
Thank You.
