### ISSUE TITLE
stock const/ stock static

### ISSUE THREAD

**Issue by Dayvison** [Zeex/pawn#158]
Will be good can use:
```c++
stock const asd = 1;
stock static asd = 1;
stock static const asd = 1;
```
works fine if use:
```c++
static const asd = 1;
```

**Comment by YashasSamaga** [comment]
```
stock const asd = 1;
stock static asd = 1;
stock static const asd = 1;
```

do not give out any error or warning on both the original compiler and Zeex' compiler.

What's the issue?

**Comment by Dayvison** [comment]
I remember this gave me errors, but i'm not able to reproduce it with the latest compiler.
Closing this now.
