### ISSUE TITLE
public variables, like public functions

### ISSUE THREAD

**Issue by Dayvison** [Zeex/pawn#165]
## Public functions
- Detect after and before definition

```pawn
#if defined PUB 
	#warning "defined-1"
#endif

forward PUB();
public PUB() { }

#if defined PUB 
	#warning "defined-2"
#endif
```
give this:
```
warning 237: user warning: "defined-1"
warning 237: user warning: "defined-2"
```

## Public variables
- Detect only after definition

```pawn
#if defined PUB 
	#warning "defined-1"
#endif

public PUB = 1;

#if defined PUB 
	#warning "defined-2"
#endif
```
give this:
```
warning 237: user warning: "defined-2"
```

**Comment by Y-Less** [comment]
Functions can be used before use, variables cant't.

**Comment by Dayvison** [comment]
i need just detect if the variable as created

**Comment by Y-Less** [comment]
This isn't really a bug - you just want to do something you can't.  Variables can only be used after declaration; by design not omission.

**Comment by Dayvison** [comment]
Yeah, i can see now. You right

**Comment by YashasSamaga** [comment]
@Zeex this should be closed?

**Comment by Dayvison** [comment]
yeah
