### ISSUE TITLE
Compatibility mode error

### ISSUE THREAD

**Issue by thebatyaZ** [Zeex/pawn#196]
When enabled [compatibility mode](https://github.com/Zeex/pawn/wiki/Compatibility-mode) compilation end with an error:

`core\impl.inc(6) : error 021: symbol already defined: "core_OnGameModeInit"`

Content main.pwn:

```
#include <a_samp>

#if defined MAX_PLAYERS
	#undef MAX_PLAYERS
#endif
#define MAX_PLAYERS (100)

#if !defined _BAWSAQ_CONFIG_INCLUDED
	#include "config"
#endif
#define _BAWSAQ_CONFIG_INCLUDED

#if !defined _BAWSAQ_HEADERS_INCLUDED
	#include "core\header"
	#include "player\header"
	#include "business\header"
#endif
#define _BAWSAQ_HEADERS_INCLUDED

#if !defined _BAWSAQ_IMPLS_INCLUDED
	#include "core\impl"
	#include "player\impl"
	#include "business\impl"
#endif
#define _BAWSAQ_IMPLS_INCLUDED

main() {}
```

Content core\impl.inc:
```
#if defined _inc_impl
	#undef _inc_impl
#endif

public OnGameModeInit()
{
	SetGameModeText(GAMEMODE_TEXT);

	#if defined core_OnGameModeInit
		return core_OnGameModeInit();
	#else
		return 1;
	#endif
}
#if defined _ALS_OnGameModeInit
	#undef OnGameModeInit
#else
	#define _ALS_OnGameModeInit
#endif

#define OnGameModeInit core_OnGameModeInit
#if defined core_OnGameModeInit
	forward core_OnGameModeInit();
#endif
```

**Comment by Y-Less** [comment]
I doubt that is a compiler bug, probably something getting included multiple times that you weren't expecting.  In fact, that code probably won't even compiler as you expect with compatability mode, since it will omit several files.

**Comment by thebatyaZ** [comment]
I use next pattern

\gamemodes\
    main.pwn
    config.pwn
    core\
        header.inc
        impl.inc
    player\
        core\
            header.inc
            impl.inc
        header.inc
        impl.inc

Why compiler included header.inc or impl.inc from path `\gamemodes\core\`, when I included it from `\gamemodes\player\`? How he comes back?

player\impl.inc:
```
#if defined _inc_impl
	#undef _inc_impl
#endif

#if !defined _BAWSAQ_IMPLS_INCLUDED
	#include "core\impl"
#endif
```

**Comment by thebatyaZ** [comment]
I'm stupid.

Include from `main.pwn` it a bad idea.

**Preferably keep up architecture:**

- source
  - core
    - header.inc
    - impl.inc
  - player
    - core
       - header.inc
       - impl.inc
    - header.inc
    - impl.inc
  - header.inc
  - impl.inc
- main.pwn
