### ISSUE TITLE
Warnings as errors

### ISSUE THREAD

**Issue by Y-Less** [Zeex/pawn#200]
Add something like `-W` to convert warnings to errors.  A common flag in other languages.

**Comment by Jeroen52** [comment]
This, I'd use this.

Because generally whenever I program and I get a warning, something in the code is wrong.

**Comment by Y-Less** [comment]
I've written a basic version (opted for `-E` instead of `-W` as it goes better with the existing `-e`).  Testing now (if I can get a build working).

**Comment by tmp64** [comment]
Does it mean that I'll get an error if a symbol hasn't been used yet?

**Comment by Zeex** [comment]
Yes, if you use the `-E` flag it will turn "unused symbol" warnings into errors (so the script won't compile).

**Comment by Y-Less** [comment]
You can still remove the symbol, mark it `stock`, use `#prgama unused`, or `#pragma warning disable 203` and `#pragma warning disable 204`.  There isn't much reason why you should be getting unused symbol warnings except during development.

**Comment by Y-Less** [comment]
And thanks @Zeex
