### ISSUE TITLE
I can't use the old version of YSI, problems with the new version!

### ISSUE THREAD

**Issue by SinnerAssist** [Zeex/pawn#207]
I can't compile with the old version of YSI package, I get error: fatal error 111: user error: "Did you do <YSI/y_hooks> instead of the required <YSI\y_hooks>?" and I have the right use of the include.

When I use the latest version of YSI package everything it's ok but the server freezes after the YSI version it's printed in the console for about 10 seconds more or less.

https://media.discordapp.net/attachments/373911268538712064/374132129300348929/unknown.png

**Comment by Y-Less** [comment]
Try this:

https://github.com/Zeex/amx_assembly/tree/Branch_FastJumpTargets

**Comment by Y-Less** [comment]
Otherwise, the answer is just wait 10 seconds - that's really not a lot of time IMHO.

**Comment by SinnerAssist** [comment]
I have to try this with the old version or with the new one?

**Comment by Y-Less** [comment]
New one.

**Comment by SinnerAssist** [comment]
A little bit better but still that delay on loading up the server. With the old version of YSI the loading was instantly, can you explain me why is like this? :D

**Comment by Y-Less** [comment]
Because YSI is doing more on startup.  I always trade RAM and startup time for execution time.  So if I can make your mode run faster by making it start slower, I will, almost every time.

**Comment by Y-Less** [comment]
Though I am also working on ways to improve the startup, it is just not as high priority since when a script runs for days or weeks, a few extra seconds at the start doesn't really matter.

**Comment by SinnerAssist** [comment]
Yeah, it's true. Thank your for the explain. I'm "scripting" in pawn since 2009, you're a real legend :D
