### ISSUE TITLE
Wrong "Symbol is truncated to 31 characters" warnings

### ISSUE THREAD

**Issue by NexiusTailer** [Zeex/pawn#208]
The problem is: when I try to transfer a large define to a new line using the '/' character, the compiler continues to count its length on a new line, stacking them together and giving the warning on the code that worked all the time well up to this version:
```
#include <a_samp>

main(){}

public OnPlayerClickPlayerTextDraw(playerid, PlayerText:playertextid)
{
	#if defined my_OnPlayerClickPlayerTextDraw
		return my_OnPlayerClickPlayerTextDraw(playerid, playertextid);
	#else
		return 0;
	#endif
}

#if defined _ALS_OnPlayerClickPlayerTextDra\
	|| defined _ALS_OnPlayerClickPlayerTD || defined _ALS_OnPlayer\
	ClickPlayerTextDraw
	#undef OnPlayerClickPlayerTextDraw
#else
	#define _ALS_OnPlayerClickPlayerTD
#endif
#define OnPlayerClickPlayerTextDraw my_OnPlayerClickPlayerTextDraw
#if defined my_OnPlayerClickPlayerTextDraw
	forward my_OnPlayerClickPlayerTextDraw(playerid, PlayerText:playertextid);
#endif
```

That is this line:
```
#if defined _ALS_OnPlayerClickPlayerTextDra\
	|| defined _ALS_OnPlayerClickPlayerTD || defined _ALS_OnPlayer\
	ClickPlayerTextDraw // <----------
```

![image](https://user-images.githubusercontent.com/13169094/32690811-b64771aa-c70d-11e7-9468-b43bc1a828d9.png)
![image](https://user-images.githubusercontent.com/13169094/32690805-9ffde9d8-c70d-11e7-9685-72050092fd77.png)

**Comment by Y-Less** [comment]
That seems like the old compiler was wrong and the new compiler was right.  `_ALS_OnPlayerClickPlayerTextDraw` is 32 characters, which is too long.  The fact that you managed to get around this limitation before using strange hacks is exactly that - a strange (and brittle) hack.

Just use the standard shortening - `_ALS_OnPlayerClickPlayerTD`, why are you making up more?

**Comment by NexiusTailer** [comment]
> Just use the standard shortening - _ALS_OnPlayerClickPlayerTD, why are you making up more?
I saw many variants of hook abbreviations, which in the end also got to this list in the code above. This is just an attempt to make detection of extraneous hooks truly universal.

**Comment by Y-Less** [comment]
The correct abbreviation of `TextDraw` is `TD`.  If you see a different one somewhere, correct them.

**Comment by NexiusTailer** [comment]
Ok, thank you. I really thought it was a compiler bug, but now, it seems, I should fix it in my scripts.
