### ISSUE TITLE
disable pragma semicolon

### ISSUE THREAD

**Issue by Banditul** [Zeex/pawn#209]
I see recently a gamemode used #pragma semicolon 0 to hide the missing semicolons that brake the gamemode at runing. Idk if its used often but should not be asa setting at all
Suggest to disable this pragma setting

**Comment by Banditul** [comment]
Well strange, was seems to work earlier with 3.10.4. I needed to remove myself from code

**Comment by Y-Less** [comment]
It works with other numbers, just not 0.

**Comment by Banditul** [comment]
Well make sense. Sorry for open an issue for a thing that was disable long ago
