### ISSUE TITLE
Array 3rd problem

### ISSUE THREAD

**Issue by Coystark** [Zeex/pawn#210]
I'm doing:

new Array [500] [200] [64];

When I put some value and compile, for example:

Array[0][99] = "dqwddqqw";

The size of AMX is 6MB, is this normal?

**Comment by Y-Less** [comment]
500 * 200 * 64 = 6400000 cells (25600000 bytes).  I make that over 24MB, so you are getting lucky with the compression there.  Why do you need such huge arrays?  I suspect the answer is one of "I don't know any other data structures".

**Comment by Coystark** [comment]
Hi Y-Less, thanks for the support, I'll explain my situation.

Let's say I'm doing an inventory system, I need to store item information in each of the players.

So I'm doing:

Items [MAX_PLAYERS] [MAX_ITEMS] [enum_ms_Items];

In the enum I'm also having to use dimensions.

What do you suggest to me? Thanks

**Comment by YashasSamaga** [comment]
Why are you having `[MAX_ITEMS][enum_items]`?

Wouldn't just `[enum_items]` suffice?

**Comment by Coystark** [comment]
No, because I need to store item information on each player.

Item information will vary from player to player.

What bothers me a lot is that difference from a 2rd array to a 3rd, opening the GameMod bare.pwn, adding:

new Array [500] [64];

And filling in with some value and then compiling, the AMX value gets 35KBs.

But just add one more dimension in the Array, that AMX gets a huge boost in size.

**Comment by Y-Less** [comment]
Yes, that huge boost in size is called maths - specifically multiplication.  If your code is `[200][64]` and you change it `[500][200][64]` you just increased your array size 500-fold.  This is not a bug, this is the compiler doing what you asked, even when what you asked is stupid.

**Comment by Coystark** [comment]
Ok I got it.
But why do you end your answers arrogantly?

Peace and thanks for your explanation :)

**Comment by Jeroen52** [comment]
He did explain exactly why the AMX was that large in his first response, and why you were lucky that the compression was decent.

Other than that, Y-Less has contributed to the community for years and is known as the "Spam Machine", we should all be happy that he is still helping us.
