### ISSUE TITLE
Source code version number is incorrect

### ISSUE THREAD

**Issue by Southclaws** [Zeex/pawn#213]
This caused much confusion while testing the sampctl auto-download/install for the compiler!

```
∆ $ /Users/southclaws/Desktop/pawnc-3.10.4-darwin/bin/pawncc
Pawn compiler 3.10.2	 	 	Copyright (c) 1997-2006, ITB CompuPhase
```

**Comment by Zeex** [comment]
It probably uses the wrong pawnc.dylib that it found somewhere in your library path. You need to replace both pawncc and pawnc.dylib when updating, or alternatively point the executable to the location of the DYLIB file by setting `DYLD_LIBRARY_PATH`:

```
export DYLD_LIBRARY_PATH=path/to/pawnc-3.10.4-darwin/lib 
path/to/pawnc-3.10.4/bin/pawncc
```

**Comment by Southclaws** [comment]
Oh I was using sampctl [which defines `LD_LIBRARY_PATH`](https://github.com/Southclaws/sampctl/blob/master/compiler/compiler.go#L123) I didn't know about the "DYLD" version.

sampctl puts each compiler version in a [separate](https://github.com/Southclaws/sampctl/blob/master/compiler/compiler.go#L84) directory though, and these directories aren't added to any environment variable. Is there any `which` style command for shared libraries I can use to find out which one it's loading?

**Comment by Southclaws** [comment]
Ah, I had a hidden libpawnc.dylib in my usr/lib directory - must have been from before I made sampctl! Sorry about the issue, thanks for the help!
