### ISSUE TITLE
I think this is a bug

### ISSUE THREAD

**Issue by 1Conan** [Zeex/pawn#31]
Pawn compiler 3.2.3664.samp                     Copyright (c) 1997-2006, ITB CompuPhase

/root/include/a_http.inc(22) : error 021: symbol already defined: "HTTP"
/root/include/YSI/internal/y_version.inc(194) : error 021: symbol already defined: "YVers_Callback"
/root/include/YSI/y_scripting.inc(86) : warning 219: local variable "addr" shadows a variable at a preceding level
/root/include/YSI/y_scripting.inc(109) : warning 219: local variable "addr" shadows a variable at a preceding level
/root/include/YSI/y_scripting.inc(299) : warning 219: local variable "addr" shadows a variable at a preceding level
/root/include/YSI/y_scripting.inc(452) : warning 219: local variable "addr" shadows a variable at a preceding level
/root/include/YSI/y_scripting.inc(571) : warning 219: local variable "addr" shadows a variable at a preceding level
/root/include/YSI/y_scripting.inc(622) : warning 219: local variable "addr" shadows a variable at a preceding level
/root/include/a_http.inc(22) : error 021: symbol already defined: "HTTP"
/root/include/YSI/internal/y_version.inc(122) : error 021: symbol already defined: "YVers_OnScriptInit"
/root/include/YSI/internal/y_version.inc(194) : error 021: symbol already defined: "YVers_Callback"
/root/include/a_http.inc(22) : error 021: symbol already defined: "HTTP"
/root/include/YSI/internal/y_version.inc(122) : error 021: symbol already defined: "YVers_OnScriptInit"
/root/include/YSI/internal/y_version.inc(194) : error 021: symbol already defined: "YVers_Callback"
/root/include/YSI/y_als.inc(59) : error 017: undefined symbol "_inc_y_als"
/root/include/YSI/y_als.inc(59) : error 010: invalid function or declaration
/root/include/a_http.inc(22) : error 021: symbol already defined: "HTTP"
/root/include/YSI/internal/y_version.inc(122) : error 021: symbol already defined: "YVers_OnScriptInit"
/root/include/YSI/internal/y_version.inc(194) : error 021: symbol already defined: "YVers_Callback"
/root/include/a_http.inc(22) : error 021: symbol already defined: "HTTP"
/root/include/YSI/internal/y_version.inc(122) : error 021: symbol already defined: "YVers_OnScriptInit"
/root/include/YSI/internal/y_version.inc(194) : error 021: symbol already defined: "YVers_Callback"
/root/include/YSI/internal/y_shortfunc.inc(96) : error 021: symbol already defined: "U@"
/root/include/YSI/internal/y_shortfunc.inc(97) : error 021: symbol already defined: "V@"
/root/include/YSI/internal/y_shortfunc.inc(100) : error 021: symbol already defined: "W@"
/root/include/YSI/internal/y_shortfunc.inc(101) : error 021: symbol already defined: "P@"
/root/include/YSI/internal/y_shortfunc.inc(102) : error 021: symbol already defined: "O@"
/root/include/a_http.inc(22) : error 021: symbol already defined: "HTTP"
/root/include/YSI/internal/y_version.inc(122) : error 021: symbol already defined: "YVers_OnScriptInit"
/root/include/YSI/internal/y_version.inc(194) : error 021: symbol already defined: "YVers_Callback"
/root/include/YSI/internal/y_funcinc.inc(60) : error 021: symbol already defined: "_@_y_funcinc_@_"
/root/include/YSI/y_hooks.inc(432) : error 021: symbol already defined: "YVers_OnScriptInit"

Compilation aborted.

26 Errors.

on windows it is compiling properly maybe a bug with undefining?

**Comment by KingCodename** [comment]
Here are the settings for **Sublime Text** (Build 3083):

*Preferences -> Package Settings -> Pawn Compiler Settings -> Edit Build Settings*
```{
	"cmd": ["pawncc.exe", "-i include", "$file", "-Z", "-;+ -(+"],
	"path": "C:/PATH/TO/YOUR/PROJECT/pawno/bin",
}```
