### ISSUE TITLE
warning 203: symbol is never used: "rouletteOffsets"

### ISSUE THREAD

**Issue by razvanxd** [Zeex/pawn#35]
I'm using the latest binaries provided on the release page. (pawncc 2014/08/31)

Declaring variable:
http://pastebin.com/H0kXEYdv

I use it as parameter in this function call (http://pastebin.com/6SrNFa73) and in combination with 'sizeof' keyword.

//Later edit: I don't know if it is indeed a problem or it is my fault ( as I'm using it in combination with a tweak that allows me to create 4 dimensional arrays ). However, I found a work-around: moving entire code from include file to gamemode ( I had that variable and some other codes declared in a include file and used in gamemode. After I moved that content to gamemode header, it compiled perfectly. )

**Comment by JernejL** [comment]
Maybe a cleaner workaround is to use #pragma unused to supress the warning?

**Comment by Y-Less** [comment]
Do you even know what `static` means?

**Comment by razvanxd** [comment]
@Y-Less: Yes, I do. However, I couldn't realise what I did wrong until the following day when I looked again over the code and I saw that array was declared as static instead of new.

**Comment by Y-Less** [comment]
Also, if you need hacks to get 4d arrays working, you are almost certainly doing something in a terrible way - you should never need something that deeply nested!
