### ISSUE TITLE
Backslashes and Linux

### ISSUE THREAD

**Issue by Mellnik** [Zeex/pawn#40]
Windows Update broke my pawn compiler so I am switching everything to my Linux computer until I fixed that.

Now after compiling the pawn compiler and typing the command:
`./pawncc main.pwn "-\(+ -;+ -O1 -d0"`

It throws me **fatal error 100: cannot read from file: "internal\y_natives"**.
Since all includes use **\** rather than **/** I wonder if there is an easy solution to get Linux to support backslashes. Replacing them in every file is not really an option.

**Comment by Y-Less** [comment]
YSI does some funky stuff with slashes.  Because of the different ways that

    x\y
    x/y
    x\y/x
    x\y\z
    x/y/x

Are handled, YSI uses a combination of them all to avoid certain other issues (most notably two includes with the same name not being included).  However, 4.0 has got better at this, as it is more well tested with Zeex's compiler, though never on Linux.

**Comment by oscar-broman** [comment]
You could use my Pawn fork or put this in Zeex's more up-to-date version: https://github.com/oscar-broman/pawn/commit/072d0c81946ee54eac339896b97d7f9c512be42c

**Comment by Zeex** [comment]
Backslashes are now allowed in compatibility mode (the -Z flag).

**Comment by Southclaws** [comment]
I'm using the latest version on Linux right now and still running into this issue:
```include/camera.inc(52) : fatal error 100: cannot read from file: "YSI\y_hooks"```
Here's my compile command:

```	pawncc \
		-iinclude \
		-Dgamemodes \
		-\;+ \
		-\(+ \
		-\\+ \
		-d3 \
		-Z \
		flintcounty.pwn
```
There is a vendored `include` directory in `gamemodes` too but YSI is in there and it works on Windows.

**Comment by Dayvison** [comment]
enable z flag with `-Z+`

**Comment by Southclaws** [comment]
Tried that, still doesn't work

**Comment by Southclaws** [comment]
Okay, it was a rogue `#pragma compat`.

Still, not a very helpful error! Is `#pragma compat` deprecated? Is it documented?

**Comment by Dayvison** [comment]
https://github.com/Zeex/pawn/wiki/Compatibility-mode
