### ISSUE TITLE
Latest version issues

### ISSUE THREAD

**Issue by Kar2k** [Zeex/pawn#42]
Okay, firstly. I've been using the latest version and it's been perfect but lately I added a new function and it just won't allow me to use this function ANYWHERE. It's like if it has a function limit.

I removed all contents of the function and it's basically a return 1;

sendPlayerVerificationCode(playerid)
{
    return 1;
}

then calling sendPlayerVerificationCode(playerid) anywhere crashes the script. Causing an 'access violation' error.

I HONESTLY can NOT recreate this outside my script.

I switched and to an old dropback version I use that only has line patches and 1 or 2 other things (11/03/2013 binary). The compiler then notified me about this error 

"logoffDateStr = (logoffTime == 0) ? "(Player / Server) Crash / Exit" : realdate(logoffTime);"

which should actually be an error but the newer compiler was ignoring that fact that it was an error.

FIX -> (Wrapping the quotes with brackets) logoffDateStr = (logoffTime == 0) ? ("(Player / Server) Crash / Exit") : realdate(logoffTime);

I believe not using brackets around the quotes was a fix done in your updated pawn compiler right?

I honestly don't know what else to say about this, but this was my experience today.

**Comment by oscar-broman** [comment]
If you search for `sendPlayerVerificationCode` everywhere else in your script, what do you find? Paste the lines here.

**Comment by Kar2k** [comment]
Nothing, only where I wanted it in my code and I attempted to use it under ongamemodeinit

// sendPlayerVerificationCode(playerid);

Really, I don't have much info on this, there's nothing I really could've done.

The only other time my compiler crashes is when I use a function with a default argument thats on the same line as a case statement in a switch.

**Comment by Kar2k** [comment]
<Kar>30 can you guys believe
[23:40:42] 20<Kar>30 if i change format(gQuery, sizeof(gQuery), "UPDATE `"#mAccounts_Table"` SET `Placed` = %d WHERE `Name` = '%s' LIMIT 1", playerData[playerid][pHits_Placed], playerNameEscaped(playerid));
[23:40:42] 20<Kar>30   
[23:40:51] 20<Kar>30 to format(gQuery, sizeof(gQuery), "UPDATE `"#mAccounts_Table"` SET `Placed` = %d WHERE `Name` = '%s' LIMIT 1", ++playerData[playerid][pHits_Placed], playerNameEscaped(playerid));
[23:40:58] 20<Kar>30 my server crashes!? wtf

Lol I added the ++ to the array to save a line, but it seems like I shouldn't do that. Everytime that was called the server crashed and all that was output was malloc shit, just memory functions

**Comment by Zeex** [comment]
I would be interesting to compare assembly code generated for that line in both cases. I can't imagine how could adding ++ to something crash the server, pretty sure it's a bug.

**Comment by Y-Less** [comment]
Do you know what the value of "pHits_Placed" is?  The only way I can think of that crashing is if the value is cellmax before the increment, both because that's an overflow and because PAWN is not very good at printing cellmin.

**Comment by Zeex** [comment]
Can MySQL handle something like `--` instead of a number in a query? (that's what format outputted for cellmin)

**Comment by Y-Less** [comment]
I have no clue, that was the only theory I could come up with at all.  Obviously more debugging is required.

**Comment by Kar2k** [comment]
well pHits_Placed per player is reset on every connection to 0, so the only place where it would bug would be when a player logs in. Also I must note, that you have a point. It was only happening when a certain player performed the command.

Ah, I just checked the database, his hits_placed is '-1694498801' somehow.

It seems that 4 players somehow have negative hits_placed, yet I only increment hits placed in the command, declare it in the enum, reset it on player entry and load it on login. I don't see how this value could've gotten altered because it's only used in those 4 places and none of my other variables have ever done this.

Thanks though, weird things seem to happen in this gamemode.

**Comment by oscar-broman** [comment]
Probably an out-of-bounds access to an array, modifying things it shouldn't.

**Comment by Y-Less** [comment]
Those don't look like overflows - they are all too close and high to be a co-incidence of a variable going past 2147483647 and looping to negative.  However, that's just a hunch given the grouping, so it could still be that if you increment them enough beyond the 32-bit variable limit.
