### ISSUE TITLE
Maximum array depth

### ISSUE THREAD

**Issue by Misiur** [Zeex/pawn#43]
Would it be possible to increase maximum array depth to 4<? Compiler flag would suffice. Example usage
```pawn
#define MAX_QUESTIONS 128
#define MAX_ANSWERS 4

enum E_TYPE {
    TYPE_ONE,
    TYPE_TWO
}

static const
     QuestionAnswers[E_TYPE][MAX_QUESTIONS][MAX_ANSWERS][64]
;
```

**Comment by Zeex** [comment]
Well, I've found the constant responsible for the maximum number of array dimensions:

https://github.com/Zeex/pawn/blob/master/source/compiler/sc.h#L53

I'm not sure if it would be sufficient to change its value alone, but the code compiled.

Is it practical to set it to something bigger than 4?

**Comment by Arkshine** [comment]
Be careful, I know SourceMod is using it and BAILOPAN said me it was kind of buggy.
Also, you might need this, which fixes some generation issue: https://hg.alliedmods.net/sourcemod-central/rev/ee044380947f
I don't know if there is others fixes around 4d.

**Comment by Zeex** [comment]
I've changed the max. number of dimensions to 4 for the sake of experiment, however that seems not enough because 4d array initialization doesn't seem to be fully supported:

```pawn
#include <a_samp>

new a[2][2][2][2] = {
    {
        {
            {1, 2}, {3, 4}
        },
        {
            {5, 6}, {7, 8}
        }
    },
    {
        {
            {11, 12}, {13, 14}
        },
        {
            {15, 16}, {17, 18}
        }
    }
};

main() {
    for (new i = 0; i < sizeof a; i++) {
        for (new j = 0; j < sizeof a[]; j++) {
            for (new k = 0; k < sizeof a[][]; k++) {
                for (new l = 0; l < sizeof a[][][]; l++) {
                    printf("a[%d][%d][%d][%d] = %d", i, j, k, l, a[i][j][k][l]);
                }
            }
        }
    }
}
```

will produce:

```pawn
a[0][0][0][0] = 1
a[0][0][0][1] = 2
a[0][0][1][0] = 3
a[0][0][1][1] = 4
a[0][1][0][0] = 1 // should be 5
a[0][1][0][1] = 2 // should be 6
a[0][1][1][0] = 3 // should be 7
a[0][1][1][1] = 4 // should be 8
a[1][0][0][0] = 5 // should be 11
a[1][0][0][1] = 6 // should be 12
a[1][0][1][0] = 7 // should be 13
a[1][0][1][1] = 8 // should be 14
a[1][1][0][0] = 11 // should be 15
a[1][1][0][1] = 12 // should be 16
a[1][1][1][0] = 13 // should be 17
a[1][1][1][1] = 14 // should be 18
```

**Comment by Misiur** [comment]
I don't know why compiler haven't complained so far, but currently there's a missing array info struct (you ported sc1.c changeset, but missed sc.h one). It prints correct values for me now

**Comment by Misiur** [comment]
Ok, so it doesn't affect ellipsis as it resides in `initials`, but I was mislead by this thing: ellipsis only supports up to 2 dimensions?
