### ISSUE TITLE
Multidimensional arrays different behaviour with compability mode

### ISSUE THREAD

**Issue by Misiur** [Zeex/pawn#53]
Try this snippet in standard compiler, and with this compiler in compability mode:
```pawn
#include <a_samp>

new foo[3][2][] = {
    {"Bar","Bar"},
    {"Boo","Boo"},
    {"Bee","Bee"}
};

main() {
    printf("%d, %s", sizeof foo, foo[0][0]);
}
```

Expected result: All is well
Actual result: error 052, multidimensional-arrays must be fully initialized 

No idea why, maybe new ellipsis support changed that.

edit: Compability mode doesn't matter, it still reports this error

**Comment by Zeex** [comment]
It compiles now but doesn't print the correct string, I'm looking into that.
