### ISSUE TITLE
The include files

### ISSUE THREAD

**Issue by oscar-broman** [Zeex/pawn#54]
For some reason, even if I move `pawncc` and `libpawnc.so` to `/usr/bin` and `/usr/lib`, it includes `include/default.inc`.
It started failing because print and printf were already defined, and it took a while until I found where they came from.

Are the default include files really needed?

**Comment by Zeex** [comment]
You mean it include the default.inc from the source tree?

**Comment by oscar-broman** [comment]
Yeah.

**Comment by Zeex** [comment]
Strange, that never happened to me. Is it in your include path?

**Comment by oscar-broman** [comment]
I just cloned the repo into `/home/user/pawn` then compiled it and copied it into `/usr`.

After that, I made a directory called `/home/user/test` and put the following in `test.pwn`:
```pawn
native print(const str[]);

main() {
	print("test");
}
```

If I try to compile:
```
hostname% pawncc test.pwn
Pawn compiler 3.2.3664.samp.6b3c30a	 	 	Copyright (c) 1997-2006, ITB CompuPhase

test.pwn(1) : error 021: symbol already defined: "print"
test.pwn(1) : error 025: function heading differs from prototype

2 Errors.
```

**Comment by Zeex** [comment]
OK, I get it, it's because you're generating cmake files in the source tree (I usually create a build directory and run cmake from there). Though I'm not sure how it knows where to find include from /usr/bin, I guess it might have something to do with rpath (the pawncc in /usr/bin still loads the libpawnc.so in your home directory).

**Comment by oscar-broman** [comment]
Yeah, you're right. Removing `libpawnc.so` fixed it.

**Comment by tr1xy** [comment]
Oh boi, I noticed that this code won't compile at all using default compiler:
```
#include <a_samp>
#include <YSI_Visual\y_commands>

main() {}
```
Also, errors are different If I include just y_va instead of y_commands for example:
```
[debug] Run time error 19: "File or function is not found"
[debug]
[debug]  PA
[debug]  PA
[debug] Run time error 19: "File or function is not found"
[debug]
[debug]  PA
[debug]  PA
Script[gamemodes/YSI_ERROR_DEBUG.amx]: Run time error 19: "File or function is not found"
```
Build system:
```
{
    "selector": "source.pwn", 
    "file_regex": "(.*?)\\(([0-9]*)[- 0-9]*\\)", 
    "cmd": [
        "pawncc.exe", 
        "$file", 
        "-o$file_path/$file_base_name", 
        "-;+", 
        "-(+", 
        "-d3"
    ], 
    "working_dir": "C:/Compiler"
}
```
