### ISSUE TITLE
Pawn Compiler on Termux

### ISSUE THREAD

**Issue by dnfive** [Zeex/pawn#573]
Hello. Has anyone tried running pawncc on termux? I get an error: cannot execute binary file: exec format error. Can you help me?
![Screenshot_20200927_140011.jpg](https://user-images.githubusercontent.com/44578321/94363278-c6e11b80-00c9-11eb-9bf2-b0e1954c1bb5.jpg)

**Comment by YashasSamaga** [comment]
You need to (cross) compile pawncc for ARM. The packages are built for x86.

**Comment by NathanKanaeru** [comment]
Open this repository:

https://github.com/Nathan-Studios/Pawn4Droid



On the release section and downloads all, and move the pawncc and pawndisasm to $PREFIX/bin and move libpawnc.so to $PREFIX/lib



Or if you want to be easier to use the Installwr Script from the GITHUB repository



Link Video

https://youtu.be/itBffLyZHWA?si=ci7GwlkWJzaGf3Nb
