### ISSUE TITLE
-i (path for include files) option for Linux compiler does not work

### ISSUE THREAD

**Issue by ziggi** [Zeex/pawn#59]
**-i** option on Windows works fine, but on Linux this ignored.

I have this file struct:
```
.
├── !compile.sh
├── !compile.bat
├── compiler
│   ├── includes
│   │   ├── a_http.inc
│   │   ├── a_npc.inc
│   │   ├── a_objects.inc
│   │   ├── a_players.inc
│   │   ├── a_sampdb.inc
│   │   ├── a_samp.inc
│   │   ├── a_vehicles.inc
│   │   ├── core.inc
│   │   ├── datagram.inc
│   │   ├── file.inc
│   │   ├── float.inc
│   │   ├── string.inc
│   │   └── time.inc
│   ├── libpawnc.so
│   ├── pawncc
│   ├── pawncc.exe
│   ├── pawncc.pdb
│   ├── pawnc.dll
│   └── pawnc.pdb
├── gamemodes
├── plugins
├── scriptfiles
└── sources
    └── Open-GTO.pwn
```

!compile.sh:
```bash
#/bin/bash

export LD_LIBRARY_PATH=$(pwd)"/compiler/:$LD_LIBRARY_PATH"

NAME="Open-GTO"

./compiler/pawncc "-;+ -(+ -icompiler/includes" sources/$NAME.pwn

if [ $(stat -c%s "$NAME.amx") -gt 0 ];
then
	mv $NAME.amx gamemodes/
else
	rm $NAME.amx
fi
```

!compile.bat:
```bat
set name=Open-GTO
compiler\pawncc.exe -;+ -(+ -icompiler/includes sources\%name%.pwn
if exist %name%.amx ^
move %name%.amx gamemodes\
pause
```

On Linux i get this error:
```
compiler/includes/a_samp.inc(17) : fatal error 100: cannot read from file: "core"
```
On Windows all works fine.

Currently i made this "hack":
I changed it in **a_samp.inc**:
```Pawn
#include <core>
#include <float>
#include <string>
#include <file>
#include <time>
#include <datagram>
#include <a_players>
#include <a_vehicles>
#include <a_objects>
#include <a_sampdb>
```
on it:
```Pawn
#include "compiler/includes/core"
#include "compiler/includes/float"
#include "compiler/includes/string"
#include "compiler/includes/file"
#include "compiler/includes/time"
#include "compiler/includes/datagram"
#include "compiler/includes/a_players"
#include "compiler/includes/a_vehicles"
#include "compiler/includes/a_objects"
#include "compiler/includes/a_sampdb"
#include "compiler/includes/a_http"
```

**Comment by Zeex** [comment]
Are you compiling from the same directory where compile.sh is? Try replacing relative paths with absolute ones, that definitely should help. You can get the absolute path to `compiler.sh` from within the script itself via something like `$(dirname $(readlink $0))` (for example, see [here](https://github.com/Zeex/samp-server-cli/blob/master/samp-server-cli)) and append your include directory to that.

**Comment by ziggi** [comment]
> Are you compiling from the same directory where compile.sh is?

Yes.

> Try replacing relative paths with absolute ones, that definitely should help. You can get the absolute path to compiler.sh from within the script itself via something like $(dirname $(readlink $0)) (for example, see here) and append your include directory to that.

I tried it, but it did not help.

I made small repo for test it: https://github.com/ziggi/pawn_linux_test
My new **!compile.sh**:
```Pawn
#/bin/bash

export LD_LIBRARY_PATH=$(pwd)"/compiler/:$LD_LIBRARY_PATH"

NAME="test"

include_path="$(dirname $(readlink -f $NAME))/compiler/includes"

./compiler/pawncc "-;+ -(+ -i$include_path" sources/$NAME.pwn

if [ $(stat -c%s "$NAME.amx") -gt 0 ];
then
	mv $NAME.amx gamemodes/
else
	rm $NAME.amx
fi
```

**Comment by Zeex** [comment]
```sh
"-;+ -(+ -icompiler/includes"
```

You can't take multiple arguments in quotes like that, they will be treated as one string. Try this instead:

```sh
"-;+" "-(+" "-icompiler/includes"
```

**Comment by ziggi** [comment]
Yeah, it's works. Thank you very much!
