### ISSUE TITLE
infinite compile time! 2048 warnings

### ISSUE THREAD

**Issue by tars-c** [Zeex/pawn#590]
### Issue description:
I'm working on a role-playing game mode. This mode is very old and is very poorly compatible with the current 3.10.10 compiler.

I don't know exactly what problem I'm experiencing right now
But... I guess, if you go over 2048 waring errors, you get unlimited compile times. (infinite loop, time)

Increase the limit on the number of warnings!
And terminate compilation with an error message.

2048 is a too small limit.
Please see the video I took and check the related content.
https://vimeo.com/469489461

User environment is vps host(ssh), Linux CentOS7.

When there are no warnings, the compiler works!
Please accept my opinion and update the compiler.

Finally, the mode I'm working on is 100,000 lines.
As an additional comment, I would also like to add an option to ignore the warning.
(Cannot set compiler option -> using sampctl)

### Workspace Information:
* Compiler version: v3.10.10 (latest)
* Command line arguments provided (or sampctl version): v1.9.1 (latest)
* Operating System: Linux Centos7 (v7.8)

**Comment by Y-Less** [comment]
Just fix them...  2048 should be more than enough to get you started.  If anything, that many warnings should be a fatal error and fail the compilation, just as 4 or 26 errors are a fatal error.

**Comment by tars-c** [comment]
@Y-Less Thanks for the comment.

You might think that the 2048 limit is enough. I also agree.
However, I think the compiler should inform the user in case of unlimited compile time!

I am not forcing the error to occur!
If you compile an old mod that hasn't done anything, you will experience unlimited compilation. (Number of mode lines: 80000 ~ 10000, large scale)

Users will be mistaken. And time will continue to be wasted.
I think the unlimited compile time issue should be improved through an update.

In case of more than 2048 warnings during compilation, a message system indicating that unlimited compilation will occur and Interrupt -> Compilation forced termination

Please consider my opinion once again.

Thank you for listening to my opinion.
The issue ends.

**Comment by Y-Less** [comment]
Unlimited compile times usually come from bugs.  If we find those bugs, we just fix them, so informing the user in those cases doesn't make any sense.  There are ways to detect user code that will compile forever (like unbounded macro recursion).  Those are possible to detect and error on, but hard, and I don't think there's any exhaustive list of cases.

As for too many warnings, the error at 2048 would prevent unlimited compilations.

**Comment by Y-Less** [comment]
Unlimited compile times usually come from bugs.  If we find those bugs, we just fix them, so informing the user in those cases doesn't make any sense.  There are ways to detect user code that will compile forever (like unbounded macro recursion).  Those are possible to detect and error on, but hard, and I don't think there's any exhaustive list of cases.

As for too many warnings, the error at 2048 would prevent unlimited compilations.
