### ISSUE TITLE
__timestamp

### ISSUE THREAD

**Issue by Y-Less** [Zeex/pawn#591]
### Issue description:

The compiler has `__date` and `__time`, but they're not much use because the date is locale dependent.  So unless you manage to list every possible month name in every locale there's no way to use them to get the compile-time timestamp (and it'll probably be wrong anyway).

Thus we should have `__timestamp` or something similar.

**Comment by Daniel-Cortez** [comment]
`__timestamp` has been implemented in #592, so this issue should probably be closed.
@pawn-lang
