### ISSUE TITLE
Crash on public different from protoype

### ISSUE THREAD

**Issue by BitFros7y** [Zeex/pawn#600]
# Issue description:
Compiler crashes if public function definition with array argument is different from declaration. To be more precise, if array argument name is different in definition/declaration
I would expect it to drop `error 025: function heading differs from prototype`

### Minimal complete verifiable example (MCVE):

```
#include <a_samp>
#include <fixes>//Not necessary, result is the same

forward OnServerQueryInfo(test[]);
public OnServerQueryInfo(crashHere[])
{
	return 1;
}
```

### Workspace Information:

* Compiler version: Pawn compiler 3.10.10
* Command line arguments provided (or sampctl version): Using sublime package by Southclaws (Relevant compiler return bellow)
```
[Finished in 1.5s with exit code 3221225477]
[cmd: ['pawncc.exe', 'C:\\Users\\Ice\\Desktop\\Samp Server\\filterscripts\\crashtest.pwn', '-oC:\\Users\\Ice\\Desktop\\Samp Server\\filterscripts/crashtest', '-;+', '-(+', '-d3']]
[dir: C:\Users\Ice\Desktop\Samp Server\pawno]
```

* Operating System: Windows 7 x64 SP1

**Comment by Daniel-Cortez** [comment]
Already fixed in #561.

**Comment by BitFros7y** [comment]
Ok, i see that was after 3.10.10 release. I will try to build compiler myself and see if its fixed. But feel free to close issue before that.
EDIT:  Compiled myself latest master and problem is still there. Was it merged? Sorry but im not that good with git.
EDIT:  Just checked code manually and it was not merged, tested it and yes it drops error like expected. Closing issue and waiting new release xD

**Comment by Daniel-Cortez** [comment]
> Compiled myself latest master and problem is still there. Was it merged?

The fix was merged into the `dev` branch; `master` is used for stable releases.
