### ISSUE TITLE
Another compilation issue

### ISSUE THREAD

**Issue by Kar2k** [Zeex/pawn#62]
Somehow in this enum I keep getting tag mismatches with the tags. It was happening with the Float: tag too but then I removed those variables as I didn't need them. I know I can just use an int for this, but I'm just reporting the issue.

```
C:\Users\Kar\Documents\SA-MP Server (CNR)\gamemodes\Kcnr.pwn(31800) : warning 213: tag mismatch
C:\Users\Kar\Documents\SA-MP Server (CNR)\gamemodes\Kcnr.pwn(67701) : warning 213: tag mismatch
C:\Users\Kar\Documents\SA-MP Server (CNR)\gamemodes\Kcnr.pwn(67754) : warning 213: tag mismatch
Pawn compiler 3.10.20150412-4-g3594c61	 	 	Copyright (c) 1997-2006, ITB CompuPhase

Header size:          33084 bytes
Code size:          3694920 bytes
Data size:         12011920 bytes
Stack/heap size:      32384 bytes; estimated max. usage: unknown, due to recursion
Total requirements:15772308 bytes

3 Warnings.
[Finished in 101.3s]
```

Lines are, respectively;

```
if(areaid == gCCTV[cctvAreaID][cctvID] && gCCTV[cctvStatus][cctvID] == true) {
```
```
if(gCCTV[cctvStatus][cctvID] != bool:disabled)
```
```
if(gCCTV[cctvStatus][index] == false) {
```

```
#define MAX_CCTV_CAMERAS			10
enum e_CCTV
{
	cctvObjectID,
	cctvCamObjectID,
	cctvBuildingID,
	cctvBuildingRobberyID,
	cctvAreaID,
	bool:cctvStatus
};
new gCCTV[e_CCTV][MAX_CCTV_CAMERAS];
```

WEIRDLY ENOUGH, it's not happening in my other enums.

As this one is just above it

```
enum e_BuildingAlarms
{
	alarmObjectID[MAX_ALARMS_PER_BUILDING],
	alarmBuildingID[MAX_ALARMS_PER_BUILDING],
	alarmBuildingRobberyID[MAX_ALARMS_PER_BUILDING],
	alarmTriggerTimer[MAX_ALARMS_PER_BUILDING],
	bool:alarmStatus[MAX_ALARMS_PER_BUILDING]
};
new gBuildingAlarm[MAX_ALARM_BUILDINGS][e_BuildingAlarms];
```

This is happening with both the last released compiler and the last commit.

--

I fixed this by swapping around 
```
new gCCTV[e_CCTV][MAX_CCTV_CAMERAS]; -> new gCCTV[MAX_CCTV_CAMERAS][e_CCTV];
```

Do the enum variables HAVE to be last?

**Comment by Y-Less** [comment]
"enum variables" (not a thing, but I'll move on) don't HAVE to be last, but they do HAVE to be in the right place depending on what you are trying to do.  In this case, they are in the wrong place because you want an array or structures, not a structure of arrays.  With the enum structure first, your code is more akin to:

```pawn


#define MAX_CCTV_CAMERAS            10
enum e_CCTV
{
    cctvObjectID[MAX_CCTV_CAMERAS],
    cctvCamObjectID[MAX_CCTV_CAMERAS],
    cctvBuildingID[MAX_CCTV_CAMERAS],
    cctvBuildingRobberyID[MAX_CCTV_CAMERAS],
    cctvAreaID[MAX_CCTV_CAMERAS],
    cctvStatus[bool:MAX_CCTV_CAMERAS]
};
new gCCTV[e_CCTV];
```

Note the location of the `bool:` tag - that's not an array of booleans, that's an array of integers indexed by a boolean, hence the tag mismatch.

**Comment by Kar2k** [comment]
Oh.. thats weird but okay. Thanks.

**Comment by oscar-broman** [comment]
Next time could you at least test with the original compiler too? This is not a place to dump code every time you get compilation problems.

**Comment by Y-Less** [comment]
Different code does different things - VERY weird!
