### ISSUE TITLE
a_samp.inc and console.inc both define print/printf

### ISSUE THREAD

**Issue by Cheaterman** [Zeex/pawn#626]
Everything in the title - SA-MP pawn scripts don't compile by default, given compiler/include/console.inc defines print/printf, which are also defined in a_samp.inc.

How does this work for everyone else? :-)

```
includes/pawno/a_samp.inc(57) : error 021: symbol already defined: "print"
includes/pawno/a_samp.inc(58) : error 021: symbol already defined: "printf"
```

**Comment by Cheaterman** [comment]
Gonna obviously comment the definitions in a_samp.inc, but I'd love to know if I'm supposed to use/find an alternative set of includes from somewhere? FWIW I've been using those for _ages_ so if the SA-MP team somehow released updates, I might not have them.

**Comment by Cheaterman** [comment]
I just realized things like ApplyAnimation arguments aren't set to const (as they probably should with this compiler). I'll also edit this, but I'm further suspecting I need a newer/fixed set of includes? Thanks in advance!

**Comment by Cheaterman** [comment]
OK! Closing. https://github.com/pawn-lang/samp-stdlib

**Comment by Cheaterman** [comment]
For completion reasons, could you please tell me if I'm supposed to also use the pawn-stdib repo instead of the compiler includes? From inspection I'd say "no" but I'd rather have some confirmation (surely good for future documentation too).

**Comment by Y-Less** [comment]
You either use pawn-stdlib and samp-stdlib, or you use the original defaults.  Not both.  Glad you found the correct ones.

**Comment by Cheaterman** [comment]
Hi @Y-Less, thanks a lot for your answer! I believe there might be a slight misunderstanding here - you mean "original defaults" as in "SAMP-team-distributed-pawno-defaults" ? I was rather meaning these: https://github.com/pawn-lang/compiler/tree/master/include

Is it OK to mix and match those somewhat? I didn't try (I preemptively took your advice) - but then again, my pawncc invokation (and my pawn library set) is a bit unusual:
```
PAWNCC_PATH=~/Dev/pawn-compiler
$PAWNCC_PATH/build/pawncc \
    -i./includes/pawn-stdlib \
    -i./includes/samp-stdlib \
    "$@"
    # This or pawn-stdlib, prolly not both?
    #-i$PAWNCC_PATH/include \
```
↑ the comment is basically what I'm asking about - as you can see my current invokation takes your advice and uses samp-stdlib + pawn-stdlib, both from pawn-lang organization GitHub (the one in charge of this very repo `pawn-lang/compiler` ).

For what it's worth, I had a little weird bug (minor visual glitch on one of my commands) with the other compiler, and this one fixed it (something to do with a failing strlen() on OnPlayerCommandText's params[]...). I am _very_ pleased with the extra correctness, and also very happy it helped me fix my code (adding const where necessary, not using compatible mode) !

**Comment by Y-Less** [comment]
Yeah, pretty sure the ones in this repo are well out of date.  Maybe we should submodule the other one here.

**Comment by Cheaterman** [comment]
Thanks again for your answer :-) I agree with you, either a submodule or a plain removal (with some associated instructions in the readme) would avoid the confusion. Nonetheless, in the meantime, people can read this issue if they have questions :-)
