### ISSUE TITLE
How do I create new native functions that can be suggested to the autotext / autocomplete system later? so far I can only build with #define only.

### ISSUE THREAD

**Issue by PutuSuhartawan** [Zeex/pawn#644]
Excuse me, I want to ask. How do I create new native functions that can be suggested to the autotext / autocomplete system later? so far I can only walk with #define only.

![image](https://user-images.githubusercontent.com/71969427/112996403-ba37a000-919e-11eb-8f8d-558f81906414.png)
![image](https://user-images.githubusercontent.com/71969427/112996436-c02d8100-919e-11eb-8848-b0bf39195e1a.png)
do you have any suggestions so that it can appear in the autotext/ autocomplete system?
![image](https://user-images.githubusercontent.com/71969427/112996502-cd4a7000-919e-11eb-8b0b-fe459c4f92de.png)
I got an inaccurate suggestion from all autocomplete because if it is #define there will be a lot of percent signs like this in this image. how to make him like a native? for which there are many suggested variables in each parameter
![image](https://user-images.githubusercontent.com/71969427/112996572-d9cec880-919e-11eb-8030-2115e00f7384.png)

### Minimal complete verifiable example (MCVE):

```
```

### Workspace Information:

* Compiler version:
* Command line arguments provided (or sampctl version):
* Operating System:

**Comment by Y-Less** [comment]
This repo is for the compiler.
