### ISSUE TITLE
Something is wrong

### ISSUE THREAD

**Issue by PatchwerkQWER** [Zeex/pawn#65]
Hi,
I have problem with latest version of your compiler patches with y_va & formatex by Slice.[

#include <a_samp>
#include <YSI\y_va>
#include <formatex>
 
main() {
 
}
 
stock Debug(debugtype, prefix[], str[], va_args<>) 
{
    printf("Hai!");
    return 1;
}

Errors:
gamemodes\tett.pwn(9) : error 001: expected token: ")", but found "<"
gamemodes\tett.pwn(9) : error 085: no states are defined for symbol "Debug"
gamemodes\tett.pwn(9) : error 055: start of function body without function header
gamemodes\tett.pwn(9 -- 10) : fatal error 107: too many error messages on one line

Compilation aborted.

Pawn compiler 3.10.20150503	 	 	Copyright (c) 1997-2006, ITB CompuPhase

4 Errors.
[Finished in 0.3s with exit code 1]
[cmd: ['pawncc.exe', 'C:\\Users\\QWER\\Desktop\\PAWN\\gamemodes\\tett.pwn', '-oC:\\Users\\QWER\\Desktop\\PAWN\gamemodes\\tett', '-;+', '-(+', '-d3', '-Z+']]
[dir: C:\Users\QWER\Desktop\PAWN\pawnoYSI4]
[path: C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Skype\Phone\]   

Thanks :)

**Comment by Zeex** [comment]
Is your YSI up-to-date? This compiled fine for me.

**Comment by PatchwerkQWER** [comment]
o.O Okay, now it's fine (maybe older version of YSI but i download it recently) 

Thanks

**Comment by PatchwerkQWER** [comment]
Now problem with y_commands

pawnoYSI4\include\YSI\..\YSI_Visual\y_commands/impl.inc(1329) : error 021: symbol already defined: "@yH_OnScriptInit@003"
pawnoYSI4\include\YSI\..\YSI_Visual\y_commands/impl.inc(1330) : error 021: symbol already defined: "@yH_OnScriptInit@003"
pawnoYSI4\include\YSI\..\YSI_Visual\y_commands/impl.inc(1369) : warning 209: function "@yH_OnScriptInit@003" should return a value

**Comment by Zeex** [comment]
Are you getting the same errors with the official compiler?

**Comment by PatchwerkQWER** [comment]
Sorry I forget test it with official compiler. Okay, it's probably problem with latest YSI becouse I have same errors. 

Thanks I will create issue
