### ISSUE TITLE
`#pragma naked` is allowed to be used on functions `main()` and `entry()`

### ISSUE THREAD

**Issue by Daniel-Cortez** [Zeex/pawn#656]
### Issue description:

The compiler allows to use `#pragma naked` on functions `main()` and `entry()` - this is clearly an oversight, as those functions are required to have stack cleanup code due to the way they're used.

### Minimal complete verifiable example (MCVE):

```Pawn
// Function main() is called from the VM. It's not meant to be naked, so defining it as one
// would cause an "invalid instruction" runtime error as soon as the script is loaded.
#pragma naked
main(){}

// Similarly to the above example, defining function entry() as naked will cause
// a runtime error when the state of "auto1" is changed to "ST1".
#pragma naked 
entry() <auto1:ST1>{}
```

### Workspace Information:

* Compiler version: 3.10.10
* Command line arguments provided (or sampctl version):
* Operating System:

**Comment by Y-Less** [comment]
That's not a mistake.  `naked` just means you'll do the stack cleanup yourself manually (i.e. in assembly).

**Comment by Daniel-Cortez** [comment]
Ah, I see. I'll close this issue then.
