### ISSUE TITLE
Adding support of long callback/function names.

### ISSUE THREAD

**Issue by JohnyMac** [Zeex/pawn#66]
I don't know if such a thing is possible or not.. But yeah we need this.
More info about what happened here: https://github.com/Misiur/YSI-Includes/issues/14

**Comment by Zeex** [comment]
Unfortunately, this can't be done. Like Y_Less stated in his comments https://github.com/Misiur/YSI-Includes/issues/14, it can't be fixed by changing just the compiler because the same limit exists in the AMX virtual machine.
