### ISSUE TITLE
/path/to/compiler/bin/pawncc: error while loading shared libraries: libpawnc.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Zorono** [Zeex/pawn#660]
### Issue description:
Information that could be useful:
- how to reproduce the problem: Try to compile any script in Ubuntu 20.10
- observed behavior: `/path/to/compiler/bin/pawncc: error while loading shared libraries: libpawnc.so: cannot open shared object file: No such file or directory`
- expected behavior: compile the script normally

### Workspace Information:

* Compiler version: 3.10.10
* Operating System: Ubuntu 20.10

**Comment by Zeex** [comment]
Where did you put `libpawnc.so`? It must be placed in some lib directory well known by ld (`/usr/lib`, `/usr/local/lib`, etc). I think you also need to run `ldconfig` after copying the `.so` file into one of those dirs. 

There also other ways to tell ld where to look for it, e.g.: `LD_LIBRARY_PATH` variable.

**Comment by Zorono** [comment]
It worked, Thank you dude :D
