### ISSUE TITLE
'array must be indexed' error when using addr.u.pri

### ISSUE THREAD

**Issue by dev-karpov0** [Zeex/pawn#677]
### Issue description:

The following code results in compilation error:
```pawn
new array[32];
new addr1 = __emit(addr.u.pri array);//error 033: array must be indexed (variable "array")
new addr2 = __emit(addr.u.pri array[0]);//Ok
```
Is it normal behavior? Both lines of code sould have the same result.

### Workspace Information:

* Compiler version:
* Command line arguments provided (or sampctl version):
* Operating System:

**Comment by Daniel-Cortez** [comment]
Yes, this is intended behavior. Universal pseudo-opcodes were created with the main purpose of being used in macros and handling the input from users (and by "users" I mean just regular users, not library writers), so their operands are supposed to be single cells.
