### ISSUE TITLE
Errors at line

### ISSUE THREAD

**Issue by BitakaXD91** [Zeex/pawn#684]
Hello, so i started making carry system. I was at finishing but this error appeard:

C:\Users\PC\Desktop\testserver\gamemodes\carry.pwn(109) : error 029: invalid expression, assumed zero
C:\Users\PC\Desktop\testserver\gamemodes\carry.pwn(109) : warning 215: expression has no effect
C:\Users\PC\Desktop\testserver\gamemodes\carry.pwn(109) : error 001: expected token: ";", but found ")"
C:\Users\PC\Desktop\testserver\gamemodes\carry.pwn(109) : error 029: invalid expression, assumed zero
C:\Users\PC\Desktop\testserver\gamemodes\carry.pwn(109) : fatal error 107: too many error messages on one line

.

Can someone help me to remove these errors? Here is the code:

CMD:carry(playerid, params[])
{
    new targetid;

    if(sscanf(params, "u", targetid))
    {
LINE 110:        return SendClientMessage(playerid, COLOR_WHITE, "За да носите човек използвайте: /carry [playerid]");
    }
    if(targetid == playerid)
    {
        return SendClientMessage(playerid, COLOR_WHITE, "Ти не можеш да носиш себе си глупчо!");
    }
    if(PlayerInfo[playerid][pHurt])
    {
        return SendMessage(playerid, COLOR_GREY, "Ти си прекалено ранен за да носиш някого. Моля изчакайте %i преди да опитате отново.", PlayerInfo[playerid][pHurt]);
    }
    if(PlayerInfo[targetid][pDraggedBy] == INVALID_PLAYER_ID)
    {
        PlayerInfo[targetid][pDraggedBy] = playerid;
        TogglePlayerControllable(targetid, 0);
        SendProximityMessage(playerid, 20.0, SERVER_COLOR, "{C2A2DA} %s хваща %s и започва да го носи", GetRPName(playerid), GetRPName(targetid));
    }
    else
    {
        PlayerInfo[targetid][pDraggedBy] = INVALID_PLAYER_ID;
        TogglePlayerControllable(targetid, 1);
        SendProximityMessage(playerid, 20.0, SERVER_COLOR, "{C2A2DA} %s спира да носи.", GetRPName(playerid), GetRPName(targetid));
    }

    return 1;
}

Ideas?

**Comment by YashasSamaga** [comment]
We do not provide scripting help here. Please use SA-MP discord or https://www.burgershot.gg/.
