### ISSUE TITLE
3d Array Declaration Bug

### ISSUE THREAD

**Issue by razvanxd** [Zeex/pawn#69]
In the latest compiler version there is a problem with 3d arrays filled at declaration.

Compiling this snippet: http://pastebin.com/Bd7KBSUW
using any older compiler version would print at runtime: "21 22 23"
20150503 compiler would print: "16 17 18"

If the array is filled at runtime, values printed are correct.

**Comment by Zeex** [comment]
Does it work with [this](https://github.com/Zeex/pawn/releases/tag/20150531) one?

**Comment by razvanxd** [comment]
Yes, it works.

**Comment by Zeex** [comment]
OK then. Thanks.
