### ISSUE TITLE
Truncated function name "symbol already defined"

### ISSUE THREAD

**Issue by AbyssMorgan** [Zeex/pawn#691]
### Minimal complete verifiable example (MCVE):

```
stock Tryg3D_GetDistanceFromPointToLine(){

}

stock Tryg3D_GetDistanceFromPointToLineEx(){

}
```

When we reach 31 characters in function name and name are similar after truncated we get error "symbol already defined"

### Workspace Information:

* Compiler version: 3.10.10
* Command line arguments provided (or sampctl version): -(+ -;+ -d3
* Operating System: Windows 10

**Comment by Y-Less** [comment]
That's true, but I'm not sure what else could happen here.  The maximum function length is the length that the internal arrays are defined as, so those are both stored internally as `Tryg3D_GetDistanceFromPointToLi`.  The extra data is lost - this is why there's a truncation warning, warnings are saying "this code is probably wrong", so IMHO the warning is really the only reasonable solution here.
