### ISSUE TITLE
Last release complier error bugs

### ISSUE THREAD

**Issue by kurta999** [Zeex/pawn#72]
C:\Users\Ati\Desktop\SERVER\pawno\include\sscanf2.inc(42) : error 001: expected token: "=", but found "["
C:\Users\Ati\Desktop\SERVER\filterscripts\rpc.pwn(249) : warning 204: symbol is assigned a value that is never used: "a"
C:\Users\Ati\Desktop\SERVER\filterscripts\rpc.pwn(415) : warning 213: tag mismatch
C:\Users\Ati\Desktop\SERVER\filterscripts\rpc.pwn(836) : error 001: expected token: "=", but found "["
C:\Users\Ati\Desktop\SERVER\filterscripts\rpc.pwn(836) : warning 217: loose indentation
C:\Users\Ati\Desktop\SERVER\filterscripts\rpc.pwn(836) : error 029: invalid expression, assumed zero
C:\Users\Ati\Desktop\SERVER\filterscripts\rpc.pwn(836) : warning 215: expression has no effect
C:\Users\Ati\Desktop\SERVER\filterscripts\rpc.pwn(836 -- 837) : error 017: undefined symbol "s_szQuery"
C:\Users\Ati\Desktop\SERVER\filterscripts\rpc.pwn(836 -- 837) : fatal error 107: too many error messages on one line

Compilation aborted.

Pawn compiler 3.10.20150621	 	 	Copyright (c) 1997-2006, ITB CompuPhase

5 Errors.

Line 42:

stock const
	SSCANF_QUIET[] = "SSCANF_QUIET", // 42
	OLD_DEFAULT_NAME[] = "OLD_DEFAULT_NAME",
	MATCH_NAME_PARTIAL[] = "MATCH_NAME_PARTIAL",
	CELLMIN_ON_MATCHES[] = "CELLMIN_ON_MATCHES",
	OLD_DEFAULT_KUSTOM[] = "OLD_DEFAULT_KUSTOM",
	OLD_DEFAULT_CUSTOM[] = "OLD_DEFAULT_CUSTOM";

	static const
		s_szLoginData[] = "Login Data",   // 836
                s_szASD[] = "asdasdasd";

**Comment by Zeex** [comment]
The patch that caused this was reverted (https://github.com/Zeex/pawn/commit/b261bacfa490b4e381ec9f76e1046f709d6ba6f7), looks like it needs more work. Closing this for now.
