### ISSUE TITLE
fatal error 100: cannot read from file: "YSI\internal\y_natives"

### ISSUE THREAD

**Issue by pedropapa** [Zeex/pawn#75]
Screenshot:
<img width="843" alt="screenshot 2015-09-24 10 46 11" src="https://cloud.githubusercontent.com/assets/2160382/10074962/8cbd230e-62a9-11e5-82b4-f7f64a743c49.png">

Why the compiler cannot read the YSI includes? it's reading the default includes just fine (a_samp, for example)

if a ran the command without -i:pawno/include I get the following error message:
```
fatal error 100: cannot read from file: "a_samp"
```

The funny thing is that I'm not using YSI includes at all. See:
<img width="1432" alt="screenshot 2015-09-24 10 57 37" src="https://cloud.githubusercontent.com/assets/2160382/10075256/2642ac0a-62ab-11e5-8246-1ef62e790626.png">

Note: I'm on a macbook running OSX 10.10.3. I'm using the latest release of Zeex/pawn.

My pawno/include directory structure is:

<img width="467" alt="screenshot 2015-09-24 10 52 47" src="https://cloud.githubusercontent.com/assets/2160382/10075142/8e012ebc-62aa-11e5-8fa5-e9c5e147cd40.png">
<img width="492" alt="screenshot 2015-09-24 10 53 21" src="https://cloud.githubusercontent.com/assets/2160382/10075143/8e024e6e-62aa-11e5-91f7-b294a1e2b4e9.png">
<img width="539" alt="screenshot 2015-09-24 10 53 45" src="https://cloud.githubusercontent.com/assets/2160382/10075141/8dfe6876-62aa-11e5-9ce2-60c2b2d46182.png">

I have a Windows 7 VM running on Parallels, if I compile the same gamemode on it using Windows version of pawn compiler, it compiles it just fine.

**Comment by Larceny-** [comment]
foreach is probably including <YSI\y_iterate>.
Try compiling with -Z tag (compatibility mode).

**Comment by pedropapa** [comment]
-Z parameter solved the problem, thanks!
