### ISSUE TITLE
Segfaults randomly on OSX

### ISSUE THREAD

**Issue by m-brian** [Zeex/pawn#76]
The compiler can crash on OSX with a segmentation fault, but it doesn't happen all the time. Sometimes it works correctly, sometimes crashes 5s, 20s into compiling. Seems random. I compiled the most recent code form the master branch. Let me know how to provide more details. 

    ./pawncc gm.pwn -i./include
    Pawn compiler 3.10	 	 	Copyright (c) 1997-2006, ITB CompuPhase
    Segmentation fault: 11

**Comment by oscar-broman** [comment]
Could you compile it with the debug configuration and run it under gdb?

To compile:
```
cd pawn
cd build
cmake ../source/compiler -DCMAKE_C_FLAGS="-m32 -fno-builtin" -DCMAKE_CXX_FLAGS="-m32 -fno-builtin" -DCMAKE_BUILD_TYPE=Debug
make
```

To run it:
```
lldb -- /path/to/pawncc -d3 file.pwn
```

After lldb opens, type `run` and hit enter.

**Comment by m-brian** [comment]
Well, after I upgraded my system along with xcode and compiled pawncc with debug symbols I wasn't able to reproduce the issue anymore. I guess it's best to close it for now, I'll report back if it reappears. 🍻
