### ISSUE TITLE
Compile Error "fatal error 100"

### ISSUE THREAD

**Issue by Jonathan-Rosewood** [Zeex/pawn#77]
The compilation is successful if you use the standard compiler.
But when you try to use your getting the error - http://prntscr.com/8phw3t
As you can see in the screenshot, the file actually exists.
Help me to solve this problem, please.

**Comment by Jonathan-Rosewood** [comment]
I had a similar problem with nested include files, but using a standard compiler.
If you are interested in the details or reproduction errors - please contact.
I decided it by reducing the number of levels of nesting.
But to go into the source code YSI I is not ready yet :)

**Comment by Y-Less** [comment]
What flags are you using to compile?  YSI needs `-;+ -(+ -Z` on this compiler (I'm not sure about the `-Z`, but I know I haven't personally tested it well without.

**Comment by Jonathan-Rosewood** [comment]
I understand that it's time to finish it because of my suspicious normality
@Y-Less you are beautiful ;)

P.S. Before that I tried to compile with flags "-;+ -v2 -d3 -\\)+ -l".
