### ISSUE TITLE
Question: trying to build on OSX

### ISSUE THREAD

**Issue by fvandillen** [Zeex/pawn#79]
Hey there,

Pretty default setup, trying to build with CMake and getting the following error when packing:

```
/Users/florianvandillen/Downloads/pawn-master/source/amx/amx.c:493:5: error: expression is not an integer constant expression
211 warnings and 1 error generated.
make[2]: *** [CMakeFiles/pawndisasm.dir/Users/florianvandillen/Downloads/pawn-master/source/amx/amx.c.o] Error 1
make[1]: *** [CMakeFiles/pawndisasm.dir/all] Error 2
make: *** [all] Error 2
```

Any ideas would be welcome!

**Comment by Zeex** [comment]
It seems that you're building for 64-bit, and that is not supported. Try doing a 32-bit build instead by running cmake like this:

```sh
cmake -DCMAKE_C_FLAGS=-m32 <rest of arguments>
```

**Comment by fvandillen** [comment]
Building correctly, thanks a lot!

Addition: I am able to compile my .pwn filterscript correctly from Atom, however when I #include another .pwn file residing in a sub-folder of my filterscripts folder, the compiler crashes.

Any ideas?

**Comment by fvandillen** [comment]
Solved it by using backslashes (read some of the other issues).

Thanks for your help!
