### ISSUE TITLE
Compiling with y_iterate results in unexpected errors

### ISSUE THREAD

**Issue by mschnitzer** [Zeex/pawn#81]
Hi,

I just tried your compiler and I finally got it up and running. Thanks btw. for this amazing work. When I compile my script (it compiles fine with the Windows compiler btw), I get these errors:
```
Pawn compiler 3.10.20150531                     Copyright (c) 1997-2006, ITB CompuPhase

gamemodes/test.pwn(20726) : warning 208: function with tag result used before definition, forcing reparse
gamemodes/test.pwn(367) : error 001: expected token: "-identifier-", but found "("
gamemodes/test.pwn(368) : error 001: expected token: "-identifier-", but found "("
gamemodes/test.pwn(424) : error 001: expected token: "-identifier-", but found "-integer value-"
gamemodes/test.pwn(439) : error 001: expected token: "-identifier-", but found "-integer value-"
gamemodes/test.pwn(506) : error 001: expected token: "-identifier-", but found "-integer value-"
gamemodes/test.pwn(507) : error 001: expected token: "-identifier-", but found "-integer value-"
gamemodes/test.pwn(530) : error 001: expected token: "-identifier-", but found "-integer value-"
gamemodes/test.pwn(569) : error 001: expected token: "-identifier-", but found "-integer value-"
gamemodes/test.pwn(584) : error 001: expected token: "-identifier-", but found "-integer value-"
gamemodes/test.pwn(633) : error 001: expected token: "-identifier-", but found "-integer value-"
gamemodes/test.pwn(684) : error 001: expected token: "-identifier-", but found "-integer value-"
gamemodes/test.pwn(953) : error 001: expected token: "-identifier-", but found "-integer value-"
gamemodes/test.pwn(954) : error 001: expected token: "-identifier-", but found "("
gamemodes/test.pwn(1042) : error 001: expected token: "-identifier-", but found "-integer value-"
gamemodes/test.pwn(1115) : error 001: expected token: "-identifier-", but found "-integer value-"
gamemodes/test.pwn(1116) : error 001: expected token: "-identifier-", but found "-integer value-"
gamemodes/test.pwn(1162) : error 001: expected token: "-identifier-", but found "-integer value-"
gamemodes/test.pwn(1180) : error 001: expected token: "-identifier-", but found "-integer value-"
gamemodes/test.pwn(1433) : error 001: expected token: "-identifier-", but found "-integer value-"
gamemodes/test.pwn(1455) : error 001: expected token: "-identifier-", but found "-integer value-"
gamemodes/test.pwn(1737) : error 017: undefined symbol "foreach"
gamemodes/test.pwn(1737) : error 029: invalid expression, assumed zero
gamemodes/test.pwn(1737) : error 017: undefined symbol "i"
gamemodes/test.pwn(1737) : fatal error 107: too many error messages on one line

Compilation aborted.


24 Errors.
```

Looking into one of these lines (all are Iterator declarations):
```pawn
new Iterator:Vehicle<MAX_VEHICLES>;
```

I compiled my script with this command:
```
pawncc gamemodes/test.pwn -Z -i:PawnStuff/include "-;+" "-(+"
```

Does someone know, what the problem is?

@Zeex 
@Y-Less

**Comment by mschnitzer** [comment]
Sorry I forgot to add that: I'm using the latest release (Pawn compiler 3.10.20150531)

**Comment by Y-Less** [comment]
Have you actually included y_iterate?  Those look like errors stemming from not having the macros.

**Comment by mschnitzer** [comment]
@Y-Less Yes, I double checked that cause of the
```
error 017: undefined symbol "foreach"
```
error.

But I figured out, that I included YSI this way:
```pawn
#include <YSI\y_iterate>
```

After I changed it to a slash, it gave me this error:
```
Pawn compiler 3.10.20150531	 	 	Copyright (c) 1997-2006, ITB CompuPhase

PawnStuff/include/YSI/y_iterate.inc(1) : fatal error 100: cannot read from file: "..\YSI_Internal\y_compilerpass"

Compilation aborted.


1 Error.
```

That's strange because the file does exist and the directory structure is also ok. Even when I change the backslash to a slash it fails.

Maybe the compiler looks in the wrong location? I mean, when the -Z option works then we can exclude that the error comes from the \

**Comment by mschnitzer** [comment]
Oh man... You wouldn't believe this but the compiler really searched at the wrong location... At least it can find now the files but what doesn't change anything. I still get the errors listed in the first post.

So, we're at the beginning. y_iterate is actually included :-)

**Comment by Y-Less** [comment]
That still sounds like something isn't being included correctly.  Either no include or the wrong version.

**Comment by mschnitzer** [comment]
@Y-Less Yes, I tested it with a fresh "installation" of `YSI`, Zeex `amx` library for PAWN and a new gamemode. It compiles fine. I'll reopen it, when I find something related to this.

**Comment by Y-Less** [comment]
The other option is to compile with -l and see what is really going on.

**Comment by mschnitzer** [comment]
I already did that. I just solved the problem by updating YSI to the newest version. Got the script compiled. Thanks.

And btw. thanks for all your libraries and so on! They're really useful ;-)
