### ISSUE TITLE
YSI compilation problem on Linux (Debian 7)

### ISSUE THREAD

**Issue by czerwony03** [Zeex/pawn#83]
Hi, 
I'm trying to compile script on linux (debian 7).
I need 3 includes made by Y_Less (y_bit, y_colours and y_va) but yours pawncc has problem with including it...
`include/y_bit.inc(107) : fatal error 100: cannot read from file: "YSI\internal\y_version"`
I know that linux directories use forward slashes, and windows use backward slashes, and i think that this is main problem, but I can't figure it out.

Uncle Google returns me to Slice thread with PRAWN [http://forum.sa-mp.com/showpost.php?p=2411497&postcount=47](url) but nothing changed :/.

I also read issues on github which involve YSI and tried some solutions:
-Z parameter  #40 
give me  
`test/prptm2.pwn(19) : fatal error 100: cannot read from file: "includes/a_samp.inc"
`

I would be gratefull for any help.

Greetings from Poland,
Mariusz

**Comment by Zeex** [comment]
I think latest YSI versions deal better various way of including files. If you still have this issue please open an issue in YSI repo(s).
