### ISSUE TITLE
Compiler for Mac OS X ?

### ISSUE THREAD

**Issue by Dutheil** [Zeex/pawn#88]
All is in the title :p

**Comment by Y-Less** [comment]
The title isn't a question, just a statement with a question mark.  These phrases will make it a question, each one being different.  "Does Slice's [...] still work?".  "How do I build the [...]?"  "Is there a [...]?"  "Why would anyone want a [...], given that the SA:MP server doesn't run on it?"  "I tried building the [...], and it didn't work for <these reasons>, why?".

So all is not in the title...

**Comment by Dutheil** [comment]
So, my question is : can we compile the source code of this compiler for Mac OS X ?

**Comment by oscar-broman** [comment]
https://github.com/Zeex/pawn/commit/f99e141b759ef330bb4e10ad441aa74c183a765a

**Comment by Y-Less** [comment]
OK, I had a pretty good idea of what your question was when I posted, but that's not even what I thought the most likely one was - so while I was being a bit infantile, you did actually prove the point.

**Comment by Dutheil** [comment]
Mhm, I will got a MacBook Pro soon, so I will like code and compile on this OS, and there I request if this compiler has a Mac OS version.

**Comment by Dutheil** [comment]
If no, can it get a Mac OS version ?

**Comment by oscar-broman** [comment]
https://github.com/Zeex/pawn/commit/f99e141b759ef330bb4e10ad441aa74c183a765a

**Comment by marcoacierno** [comment]
It works on Macbook pro. 

I just used the commands of travis.yml and appveyor.yml to compile it.

Use -i'' to specify the include/ path.

[pawncc.zip](https://github.com/Zeex/pawn/files/200771/pawncc.zip)
