### ISSUE TITLE
Issue with -e param

### ISSUE THREAD

**Issue by Dayvison** [Zeex/pawn#89]
Using the paramter -e not show infos, and other method show.(Sorry bad english, example after)

CMD 1:
```
pawno/pawncc.exe "gamemode\main.pwn" -D"gamemode" -;+ -(+ -Z -d3 -e"output.tmp" -i"gamemode"
```
Result(In the file output.tmp)
```
main.pwn(5) : warning 203: symbol is never used: "var"
```
CMD 2:
```
pawno/pawncc.exe "gamemode\main.pwn" -D"gamemode" -;+ -(+ -Z -d3 -i"gamemode"
```
Result(In the bash)
```
Pawn compiler 3.10.20150531                     Copyright (c) 1997-2006, ITB CompuPhase

main.pwn(5) : warning 203: symbol is never used: "var"
Header size:           x bytes
Code size:            x bytes
Data size:            x bytes
Stack/heap size:      x bytes; estimated max. usage: unknown, due to recursion
Total requirements:  x bytes

1 Warning.
```

**Comment by oscar-broman** [comment]
`-e<name> set name of error file (quiet compile)`

The last part, *quiet compile*, means that errors will not be displayed in the console (only the file).

**Comment by Dayvison** [comment]
Yeah, but in the file should the infos.
this
```
Pawn compiler 3.10.20150531                     Copyright (c) 1997-2006, ITB CompuPhase

Header size:           x bytes
Code size:            x bytes
Data size:            x bytes
Stack/heap size:      x bytes; estimated max. usage: unknown, due to recursion
Total requirements:  x bytes

1 Warning.
```

**Comment by Y-Less** [comment]
Try using `-v`.

**Comment by Dayvison** [comment]
No give any change.

**Comment by oscar-broman** [comment]
That information should not be in the error file.

You're correct when you say that it's not visible in any place when compiling with `-e`, which is because of quiet compile.

This is the behavior of the Pawn compiler for SA-MP also.

**Comment by Dayvison** [comment]
Ok, thanks oscar. But have other way to send the output to a file, giving the information? maybe a batch, 
```
>output.txt (
) type output.txt
```
But this, give only time(At end), not similar to pawn(In progress)

**Comment by Y-Less** [comment]
```
[compile command] > output.txt 2>&1
```

**Comment by oscar-broman** [comment]
You could do this:
```
pawncc test.pwn 2>errors.txt >info.txt
```

If you have Windows, a few extra steps are required:

1. Download a Linux OS
2. Uninstall Windows
3. Install Linux

**Comment by Y-Less** [comment]
To be fair, redirection works on Windows too.

**Comment by oscar-broman** [comment]
Oh.. TIL! :smile:

**Comment by Y-Less** [comment]
Though otherwise, yours is good advice!

**Comment by Dayvison** [comment]
Ok thanks guys ^^.
