### ISSUE TITLE
pawn.cfg is (not)missing error.

### ISSUE THREAD

**Issue by NegativeIQ** [Zeex/pawn#90]
Every time i try to compile anything i get these:
```
ø4Ä(0) : fatal error 100: cannot read from file: "F:\Games\Gta San Andreas\SA-MP Servers\Main Server\pawno\pawn.cfg"

Compilation aborted.


1 Error.
```

That file (pawn.cfg) is there like forever and it works with normal pawn compiler that comes with samp server package. It only contains -d0 flag. If i remove it, everything compiles just fine...Also file has right permissions so its not that as i checked at least twice. While i can live without debugging information i would like to have it for CrashDetect plugin as that saved my life couple of times.

If it makes any difference im on Windows 7 32bit (or x86 if you like it that way...). While i can live without -d0 flag i would like to have it for crash detect plugin just in case

**Comment by Zeex** [comment]
Does the file actually exist at `F:\Games\Gta San Andreas\SA-MP Servers\Main Server\pawno\pawn.cfg`?

**Comment by NegativeIQ** [comment]
Yes it is i always have only one pawno in my PC and its always in main server (stock samp server package).
