### ISSUE TITLE
Random Seed

### ISSUE THREAD

**Issue by Crayder** [Zeex/pawn#93]
Currently, `IL_StandardRandom_seed` is set to the current time the first time `random` is called.

Instead, we could have a function to seed it ourselves. The function could simply set `IL_StandardRandom_seed`.

If we used the function before the first time we used `random` it would never use the time.
If we used it after, it would've used the time until we set it manually.
If we never used it, `random` would act as it normally does.

**Comment by Crayder** [comment]
Could be as simple as this:

	static cell AMX_NATIVE_CALL core_srandom(AMX *amx,const cell *params)
	{
	    IL_StandardRandom_seed = (unsigned long)params[1];
	    return 1;
	}

With native line:

	{ "srandom",       core_srandom },

---------------------

I'll just make a pull request...

**Comment by Crayder** [comment]
Of course however, since it's a native, only people who know that it exists here will be able to use it.

>native srandom(seed);

**Comment by oscar-broman** [comment]
Are you using the runtime for something?

**Comment by Crayder** [comment]
>Are you using the runtime for something?

Not sure what you mean...

I'm just suggesting adding a function to seed the random function.

**Comment by oscar-broman** [comment]
Ok, but you do realize adding a function there will not make it work on a SA-MP server? The server's runtime can't be easily changed.

This just compiles an AMX, and the only information the AMX has about native functions are their names.

**Comment by Crayder** [comment]
No actually I didn't think about that... xD
Not sure what I was getting at yesterday.
