### ISSUE TITLE
Missing MSVCR100.DLL

### ISSUE THREAD

**Issue by pds2k12** [Zeex/pawn#99]
This error shows every time I try to compile on Windows 10 Pro with the pawn patch, iot was working fine before in Windows 8.1 but now it doesn't seem to work and causing a lot of issues on Windows 10.
 Error: http://i.imgur.com/o6oW6fU.png

**Comment by Zeex** [comment]
You need to install Visual C++ 2010 libraries (the 32-bit version, even if you system is 64 bit).
